name: CI/CD Pipeline

on:
  push:
    # branches:
    #   - develop
    #   - master
  pull_request:
    branches:
      - develop
      - master

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest  # Using the ubuntu-latest runner, no container specified

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ensure deploy.sh is executable
        run: chmod +x ./scripts/app/build.sh
        
      - name: Build project
        run: |
          ./scripts/app/build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            serverless.yml
            build/ci-scripts.zip
            build/libs/*.jar

  test:
    runs-on: ubuntu-latest  # Using the ubuntu-latest runner, no container specified
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ensure deploy.sh is executable
        run: chmod +x ./scripts/app/test.sh
        
      - name: Run tests
        run: ./scripts/app/test.sh
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/*/*.xml

  deploy_dev:
    runs-on: ubuntu-latest  # Using the ubuntu-latest runner, no container specified
    needs: [test]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: dev
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ensure deploy.sh is executable
        run: chmod +x ./scripts/app/deploy.sh

      - name: Unzip and deploy to Dev
        run: |
          ./scripts/app/deploy.sh
          
  deploy_qa:
    runs-on: ubuntu-latest  # Using the ubuntu-latest runner, no container specified
    needs: [deploy_dev]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: qa
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ensure deploy.sh is executable
        run: chmod +x ./scripts/app/deploy.sh
        
      - name: Unzip and deploy to QA
        run: |
          ./scripts/app/deploy.sh
          
  deploy_uat:
    runs-on: ubuntu-latest  # Using the ubuntu-latest runner, no container specified
    needs: [test]
    if: github.ref == 'refs/heads/master'
    environment:
      name: uat
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip and deploy to UAT
        run: |
          ./scripts/app/deploy.sh

  deploy_prodt:
    runs-on: ubuntu-latest  # Using the ubuntu-latest runner, no container specified
    needs: [deploy_uat]
    if: github.ref == 'refs/heads/master'
    environment:
      name: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip and deploy to prod
        run: |
          ./scripts/app/deploy.sh
          
